### ISSUE TITLE
Password reset in admin broken

### ISSUE THREAD

**Issue by tobiasmcnulty** [caktus/django-opendebates#242]
Clicking "Change password" in the admin gives you a 500 error, and this in the logs:

```
2019-08-16T16:32:40.828193+00:00 app[web.1]: Traceback (most recent call last):
2019-08-16T16:32:40.828196+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
2019-08-16T16:32:40.828198+00:00 app[web.1]:     response = response.render()
2019-08-16T16:32:40.828200+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/response.py", line 158, in render
2019-08-16T16:32:40.828202+00:00 app[web.1]:     self.content = self.rendered_content
2019-08-16T16:32:40.828204+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
2019-08-16T16:32:40.828208+00:00 app[web.1]:     content = template.render(context, self._request)
2019-08-16T16:32:40.828209+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
2019-08-16T16:32:40.828212+00:00 app[web.1]:     return self.template.render(context)
2019-08-16T16:32:40.828213+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 210, in render
2019-08-16T16:32:40.828216+00:00 app[web.1]:     return self._render(context)
2019-08-16T16:32:40.828217+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
2019-08-16T16:32:40.828220+00:00 app[web.1]:     return self.nodelist.render(context)
2019-08-16T16:32:40.828222+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 905, in render
2019-08-16T16:32:40.828224+00:00 app[web.1]:     bit = self.render_node(node, context)
2019-08-16T16:32:40.828225+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
2019-08-16T16:32:40.828229+00:00 app[web.1]:     return node.render(context)
2019-08-16T16:32:40.828231+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
2019-08-16T16:32:40.828233+00:00 app[web.1]:     return compiled_parent._render(context)
2019-08-16T16:32:40.828234+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
2019-08-16T16:32:40.828236+00:00 app[web.1]:     return self.nodelist.render(context)
2019-08-16T16:32:40.828238+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 905, in render
2019-08-16T16:32:40.828240+00:00 app[web.1]:     bit = self.render_node(node, context)
2019-08-16T16:32:40.828242+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
2019-08-16T16:32:40.828244+00:00 app[web.1]:     return node.render(context)
2019-08-16T16:32:40.828246+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
2019-08-16T16:32:40.828248+00:00 app[web.1]:     return compiled_parent._render(context)
2019-08-16T16:32:40.828250+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
2019-08-16T16:32:40.828252+00:00 app[web.1]:     return self.nodelist.render(context)
2019-08-16T16:32:40.828254+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 905, in render
2019-08-16T16:32:40.828256+00:00 app[web.1]:     bit = self.render_node(node, context)
2019-08-16T16:32:40.828258+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
2019-08-16T16:32:40.828260+00:00 app[web.1]:     return node.render(context)
2019-08-16T16:32:40.828262+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/defaulttags.py", line 507, in render
2019-08-16T16:32:40.828264+00:00 app[web.1]:     six.reraise(*exc_info)
2019-08-16T16:32:40.828266+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/defaulttags.py", line 493, in render
2019-08-16T16:32:40.828269+00:00 app[web.1]:     url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
2019-08-16T16:32:40.828271+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/urlresolvers.py", line 578, in reverse
2019-08-16T16:32:40.828274+00:00 app[web.1]:     return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
2019-08-16T16:32:40.828276+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/urlresolvers.py", line 495, in _reverse_with_prefix
2019-08-16T16:32:40.828278+00:00 app[web.1]:     (lookup_view_s, args, kwargs, len(patterns), patterns))
2019-08-16T16:32:40.828281+00:00 app[web.1]: NoReverseMatch: Reverse for 'list_ideas' with arguments '()' and keyword arguments '{}' not found. 1 pattern(s) tried: ['(?P<prefix>[-\\w]+)/$']
```

**Comment by tobiasmcnulty** [comment]
Fixed by #254
